title = "Stefan Maron blog"
baseURL = 'https://stefanmaron.onrender.com'

# This is what goes in <html lang="">
languageCode = 'en-us'

theme = "hugo-blog-awesome"

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = '' # G-MEASUREMENT_ID

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

# To enable Disqus comments, provide Disqus Shortname below.
# To disable Disqus comments, simply leave the field empty or remove the next line
disqusShortname = ''

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[menu]
  [[menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="OpenSourceALProjects"
    name = 'OpenSourceApps'
    url = '/OpenSourceALProjects/'
    weight = 30
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 40

[params]
  sitename = "Awesome hugo blog"
  defaultColor = "dark" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "Technical blog about Business central stuff"
  mainSections = ['posts']
  toc = false # set to false to disable table of contents 'globally'
  goToTop = true # set to false to disable 'go to top' button
  additionalScripts = ['js/custom.js', 'js/custom-2.js']

[params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Stefan Maron"
  name = "Stefan Maron"
  description = "Everything that comes to my mind, mostly related to Business Central, AL development and everything around it."

# Allow to override webmanifest options
[params.webmanifest]
  name = "stefanmaron" # will use "params.sitename" or "title" by default
  short_name = "stefanmaron" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"

# Allow to override `browserconfig.xml` params (configuration for windows embeded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
name = "github"
url = "https://github.com/stefanmaron"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/channel/UC96RLsspoArRJu6dhwkOsWQ"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/stefanmaron"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/stefan-maron-709928206/"

[[params.socialIcons]]
name = "buymeacoffee"
url = "https://www.buymeacoffee.com/stefanmaron"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"
